# Generated by Django 2.2.17 on 2020-11-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='staticfiles')),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'researches',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.AddField(
            model_name='news',
            name='added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=1),
            preserve_default=False,
        ),
    ]
