# Generated by Django 2.2.17 on 2020-11-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201127_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Research',
        ),
    ]
