# Generated by Django 2.2.17 on 2021-01-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
