# Generated by Django 2.2.17 on 2020-11-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_news_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
    ]
