# Generated by Django 2.2.17 on 2021-01-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default='', max_length=40),
        ),
    ]
