# Generated by Django 2.2.17 on 2020-11-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_member_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='queue',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
