# Generated by Django 2.2.17 on 2020-11-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201128_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='queue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
