# Generated by Django 5.0 on 2024-02-18 20:31

from django.db import migrations, models


def add_position_to_article(apps, schema_editor):
    Article = apps.get_model("pages", "Article")
    for i, article in enumerate(Article.objects.order_by("timestamp").all()):
        article.position = i
        article.save()


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_article_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="authors",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="rest",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.TextField(),
        ),
    ]
